//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por ProyectoFinal.rc
//
#define DLG_INICIARSESION               101
#define IDD_VUSUARIO2                   102
#define IDR_MENU2                       103
#define DLG_INFORMACION_VENDEDOR        107
#define DLG_REGISTROUSUARIO             108
#define DLG_PRINCIPAL                   110
#define DLG_AGREGARENVIO                111
#define DLG_AGREGARPRODUCTO             113
#define DLG_BORRARENVIO                 115
#define DLG_BORRARPRODUCTO              116
#define DLG_EDITARENVIO                 117
#define DLG_EDITARPRODUCTO              118
#define DLG_MOSTRARENVIO                119
#define DLG_MOSTRARPRODUCTO             121
#define IDR_MENU1                       123
#define IDR_MENU3                       124
#define BTN_ACEPTARUSUARIO              1001
#define EB_USUARIO                      1002
#define CB_ACCIONES                     1003
#define EB_CONTRASENA                   1004
#define BTN_NUEVO                       1005
#define BTN_ACCION                      1006
#define BTN_NUEVOENVIO                  1007
#define LB_PEDIDOS                      1008
#define BTN_ENUEVO                      1011
#define BTN_NU_CREAR                    1012
#define EB_NU_USUARIO                   1013
#define EB_NU_CONTRASENA                1014
#define BTN_ECAMBIO                     1016
#define BTN_EMOSTRAR                    1017
#define BTN_EBAJA                       1018
#define BTN_UFOTO                       1019
#define EB_UNOMBRE                      1020
#define EB_UALIAS                       1021
#define BTN_UGUARDAR                    1022
#define BTN_UCANCELAR                   1023
#define CB_APRODUCTO                    1024
#define BTN_AREGISTRAR                  1025
#define EB_ACANTIDAD                    1026
#define EB_APRECIO                      1027
#define EB_ACALLE                       1028
#define EB_ACOLONIA                     1029
#define EB_ACIUDAD                      1031
#define EB_AESTADO                      1032
#define DTC_AFECHAENVIO                 1033
#define EB_AMENSAJE                     1034
#define EB_PPRECIO                      1035
#define EB_PCODIGO                      1036
#define EB_PMARCA                       1037
#define EB_PNOMBRE                      1039
#define EB_PCANTIDAD                    1040
#define EB_PDESCRIPCION                 1041
#define PC_PFOTO1                       1042
#define PC_PFOTO2                       1043
#define BTN_PFOTO                       1044
#define BTN_PAGREGAR                    1045
#define PC_UFOTO                        1046
#define BTN_PFOTO2                      1047
#define BTN_BEBAJA                      1049
#define CB_BEENVIO                      1050
#define EB_BEDATOS                      1051
#define CB_BPPRODUCTO                   1052
#define EB_BPDATOS                      1053
#define BTN_BPBAJA                      1054
#define EB_CPNOMBRE                     1065
#define EB_CPCANTIDAD                   1066
#define EB_CPPRECIO                     1067
#define EB_CPCODIGO                     1068
#define EB_CPMARCA                      1069
#define EB_CPDESCRIPCION                1070
#define BTN_CPCAMBIO                    1071
#define PC_CPFOTO1                      1072
#define BTN_CPFOTO                      1073
#define PC_CPFOTO2                      1074
#define BTN_CPFOTO2                     1075
#define EB_ACODIGO                      1076
#define BTN_CECAMBIAR                   1077
#define DTC_CEFECHAENVIO                1078
#define EB_CEMENSAJE                    1079
#define CB_CEESTADO                     1080
#define EB_CECIUDAD                     1081
#define EB_CECOLONIA                    1082
#define EB_CECALLE                      1083
#define EB_CEESTADO                     1084
#define EB_CEPRECIO                     1085
#define EB_CECANTIDAD                   1086
#define CB_CEPRODUCTO                   1087
#define CB_MEPRODUCTO                   1088
#define CB_CPBUSCAR                     1089
#define IDC_CEBUSCAR                    1090
#define EB_MECANTIDAD                   1091
#define EB_MEPRECIO                     1092
#define EB_MECALLE                      1093
#define EB_MECOLONIA                    1094
#define EB_MECIUDAD                     1095
#define EB_MESTADO                      1096
#define DTC_MEFECHAENVIO                1097
#define EB_MEPROD                       1097
#define EB_MEMENSAJE                    1098
#define EB_MPDESCRIPCION                1099
#define CB_MPNOMBRE                     1100
#define EB_MPCODIGO                     1101
#define EB_MPCANTIDAD                   1102
#define EB_MPPRECIO                     1103
#define EB_MPMARCA                      1104
#define PC_MPFOTO1                      1105
#define PC_MPFOTO2                      1106
#define BTN_NU_CANCELAR                 1107
#define EB_UFOTO                        1108
#define EB_PFOTO1                       1109
#define EB_PFOTO2                       1110
#define EB_CPFOTO1                      1111
#define EB_CPFOTO2                      1112
#define EB_MPFOTO1                      1113
#define EB_MPFOTO2                      1114
#define EB_MFECHA                       1116
#define LB_BEDATOS                      1118
#define LB_BPDATOS                      1119
#define TC_AE                           1120
#define PC_AE                           1121
#define TC_AP                           1122
#define PC_AP                           1123
#define PC_BE                           1124
#define TC_BE                           1125
#define PC_BP                           1126
#define TC_BP                           1127
#define PC_CE                           1128
#define TC_CE                           1129
#define PC_CP                           1130
#define TC_CP                           1131
#define TC_M                            1132
#define PC_M                            1133
#define PC_ME                           1134
#define TC_ME                           1135
#define PC_MP                           1136
#define TC_MP                           1137
#define IDC_DATETIMEPICKER1             1138
#define ID_VER_INFORMACI40001           40001
#define ID_VER_PRODUCTOS                40002
#define ID_VER_ENV40003                 40003
#define ID_PRODUCTOS                    40004
#define ID_ENV40005                     40005
#define ID_PRODUCTOS_AGREGAR            40006
#define ID_PRODUCTOS_DARDEBAJA          40007
#define ID_PRODUCTOS_CAMBIARINFORMACI40008 40008
#define ID_PRODUCTOS_MOSTRAR            40009
#define ID_ENV40010                     40010
#define ID_SALIR                        40011
#define ID_SALIRDELPROGRAMA_SALIR       40012
#define ID_SALIR40013                   40013
#define ID_SALIR_SALIR                  40014
#define ID_MOSTRAR_INFORMACI40015       40015
#define ID_INFORMACI40016               40016
#define ID_INFORMACI40017               40017
#define ID_REGRESAR_MEN40018            40018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
